name: healthy_dog_calculator
description: A new Flutter project.


publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  hexcolor: ^2.0.7
  font_awesome_flutter: ^10.1.0
  dropdown_formfield: ^0.1.4
  http: ^0.13.4
  flutter_dotenv: ^5.0.2
  get: ^4.6.5
  flutter_launcher_icons: ^0.9.3
  flutter_native_splash: ^2.2.6
  intl: ^0.17.0
  flutter_spinkit: ^5.1.0
  rounded_loading_button: ^2.1.0
  
  gcloud: ^0.8.5
  googleapis_auth: ^1.3.1
  mime: ^1.0.2
  image_picker: ^0.8.5+3
  provider: ^6.0.3
  firebase_core: ^1.20.0
  firebase_database: ^9.1.0
  firebase_auth: ^3.6.2
  cloud_firestore: ^3.4.3
  getwidget: ^3.0.1
  flutter_gradients: ^1.0.0+3
  flutter_screenutil: ^5.5.3+2
  
    
flutter_icons:
  image_path: "assets/images/pets_app_icon.PNG"  
  android: true
  ios: true

dev_dependencies:
  flutter_test:
    sdk: flutter

  

  flutter_lints: ^2.0.0


flutter:


  uses-material-design: true

  assets:
    - assets/images/
    - .env
    - assets/credentials.json
    - assets/data/


